### PR TITLE
Azure support using new RM

### PR DESCRIPTION
**Pull request by mbrehovsky**

### CODE REVIEW

**Comment by jonmort** [comment]
LGTM, I have no idea about azure-rm though

**Comment by mattohope** [comment]
+1, lets wait to see what happens with the open fog-azure-rm issues before merging

**Comment by mattohope** [comment]
I think we can merge this now, there will possibly to some more changes (like making the assignment of a public IP optional) but the current functionality works well, i have been testing solidly for the last two days.

Please comment back if you are still ok for this to be merged

**Comment by jonmort** [comment]
I'm happy 👍

**Pull request merged**
